### ISSUE TITLE
create Theme using createTheme

### ISSUE THREAD

**Issue by F4stella** [Narantsatsralt05/red-cross-repo#13]
haana ch code bichij baigaa hun heregtei ungu ,font style , hemjeegee duudaad ashiglaj bolhoor theme uusgeh.
Uusgehdee theme dotroo{
-palette(colors)
-typography(fontstyles)
-spacing(zai)
-breakpoints(xs ,sm ,xl ... )
}
MUI ashiglaj hiine
https://mui.com/customization/theming/

**Comment by Munkhzulne** [comment]
Eniig designiihand heleed garguulchi
