### ISSUE TITLE
Input component using styled-component

### ISSUE THREAD

**Issue by xacaag** [Narantsatsralt05/red-cross-repo#14]
Props:
1. Title
2. BorderWidth
3. BorderColor
4. BorderRadius
5. Size
<img width="379" alt="Screen Shot 1400-12-04 at 17 13 07" src="https://user-images.githubusercontent.com/87753283/155290079-95646e98-fd4e-4a7c-9012-d59078aa98c3.png">
<img width="756" alt="Screen Shot 1400-12-04 at 17 14 21" src="https://user-images.githubusercontent.com/87753283/155290167-1a749e43-7de3-47eb-b2e2-edc974707c5c.png">
<img width="443" alt="Screen Shot 1400-12-04 at 17 16 14" src="https://user-images.githubusercontent.com/87753283/155290444-27012f8a-8168-48a9-ad7f-97beb69aefb1.png">

**Comment by Munkhzulne** [comment]
Input iim bailgamaargu bnaa dood talin sain duriin ajil bol dropdown gedg component baina. Inputaa yaj hiih talaar dahij bodii
