### ISSUE TITLE
[page] create Login page using component

### ISSUE THREAD

**Issue by Nasaa1234** [Narantsatsralt05/red-cross-repo#56]
zaa ene deer bol Login page iig hiinee ene ni humuusiig burtgej avna
Tuugii yr ni back end ee duusgasan (zasah zuil bga) 
zurag ednaraa goy buten oruulaad yg tag hiine
response toi bichne
<img width="876" alt="Screen Shot 2022-03-18 at 19 00 32" src="https://user-images.githubusercontent.com/96171370/158991403-64e6cb6c-8b70-4898-a30a-018ddbbdab75.png">

**Comment by Tuugii0507** [comment]
back end deer zasah zuil bhku za XD

**Comment by Tuugii0507** [comment]
zaza bi eniig avaad hiiydeee XD
